# Generated by Django 5.2.13 on 2026-04-29 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('vehicle', 'Vehicle Loan')], max_length=20)),
                ('loan_amount_rupees', models.FloatField()),
                ('tenure_months', models.IntegerField()),
                ('annual_income_rupees', models.FloatField()),
                ('monthly_expenses_rupees', models.FloatField()),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business_owner', 'Business Owner'), ('unemployed', 'Unemployed')], max_length=30)),
                ('existing_loans_count', models.IntegerField(default=0)),
                ('existing_emi_rupees', models.FloatField(default=0)),
                ('credit_score', models.IntegerField()),
                ('vehicle_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('risk_score', models.FloatField(default=50)),
                ('user_explanation', models.TextField(default='')),
                ('shap_factors_json', models.TextField(default='[]')),
                ('improvement_suggestions_json', models.TextField(default='[]')),
                ('fairness_check_passed', models.BooleanField(default=True)),
                ('fairness_note', models.TextField(blank=True, null=True)),
                ('banker_decision', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('banker_note', models.TextField(blank=True, null=True)),
                ('banker_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('banker', 'Banker'), ('regulator', 'Regulator')], default='user', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
