# Generated by Django 5.2.13 on 2026-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_feature_values_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('csv_user_id', models.CharField(db_index=True, max_length=20)),
                ('amount', models.FloatField()),
                ('txn_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('timestamp', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(max_length=20)),
                ('merchant', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CsvUserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_user_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('income_regularity', models.FloatField(default=0)),
                ('spending_consistency', models.FloatField(default=0)),
                ('bill_payment_ratio', models.FloatField(default=0)),
                ('savings_rate', models.FloatField(default=0)),
                ('emi_burden_ratio', models.FloatField(default=0)),
                ('upi_activity_volume', models.FloatField(default=0)),
                ('rent_payment_regularity', models.FloatField(default=0)),
                ('cash_withdrawal_ratio', models.FloatField(default=0)),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_age_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cibil_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='csv_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(default='salaried', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='existing_emi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loan_type_preference',
            field=models.CharField(default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='annual_income_rupees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(default='salaried', max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_expenses_rupees',
            field=models.FloatField(default=0),
        ),
    ]
