# Generated by Django 5.2.13 on 2026-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_csvtransaction_csvuserfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_user_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=12)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('pan', models.CharField(default='', max_length=12)),
                ('aadhaar', models.CharField(default='', max_length=16)),
                ('marital_status', models.CharField(default='single', max_length=15)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=8)),
                ('residence_type', models.CharField(default='rented', max_length=20)),
                ('years_at_address', models.IntegerField(default=2)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('job_role', models.CharField(default='', max_length=80)),
                ('work_experience', models.IntegerField(default=2)),
                ('salary_credit', models.CharField(default='bank_transfer', max_length=20)),
                ('bank_name', models.CharField(default='SBI', max_length=50)),
                ('account_number', models.CharField(default='', max_length=20)),
                ('ifsc', models.CharField(default='', max_length=12)),
                ('account_type', models.CharField(default='savings', max_length=15)),
            ],
        ),
    ]
