# Generated by Django 5.2.13 on 2026-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_demoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='current_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='previous_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64),
        ),
    ]
